# API Keys for LLM services
OPENAI_API_KEY=s...
GEMINI_API_KEY=AQ.Ab8RN6LtsG5IKsymMEZMKOq_UoTR5B6NIBQUdF6iukYhuATuDQ

# Set to: OPENAI, GEMINI, OPENAI-CLASSES, GEMINI-CLASSES
AI_LLM=GEMINI-CLASSES

# Logging configuration: OFF, ERROR, WARN, INFO, DEBUG, TRACE
LOG_LEVEL=INFO

# Test config
temperature=0.1
max_tokens=150

